source "https://rubygems.org"

ruby "3.3.4"

gem "rails", "~> 7.1.3"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "sprockets-rails", "~> 3.4"
gem "bcrypt", "~> 3.1"
gem "bootsnap", "~> 1.18", require: false
gem "rexml", "~> 3.3"
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

group :test do
  gem "minitest-reporters", "~> 1.6"
end
